### ISSUE TITLE
Compiler warnings:  format-truncation

### ISSUE THREAD

**Issue by pmembrey** [zma/zlog#1]
Hi,

I hit this issue when compiling with GCC 8 with `-Wall`:

    zlog/zlog.c: In function ‘zlogf_time’:
    zlog/zlog.c:172:51: error: ‘.’ directive output may be truncated writing 1 byte into a region of size between 0 and 127 [-Werror=format-truncation=]
         snprintf(buffer, ZLOG_BUFFER_STR_MAX_LEN, "[%s.%06lds] ", timebuf, tv.tv_usec);
                                                       ^
    zlog/zlog.c:172:5: note: ‘snprintf’ output between 12 and 153 bytes into a destination of size 128
         snprintf(buffer, ZLOG_BUFFER_STR_MAX_LEN, "[%s.%06lds] ", timebuf, tv.tv_usec);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    zlog/zlog.c: In function ‘zlog_time’:
    zlog/zlog.c:203:51: error: ‘.’ directive output may be truncated writing 1 byte into a region of size between 0 and 127 [-Werror=format-truncation=]
         snprintf(buffer, ZLOG_BUFFER_STR_MAX_LEN, "[%s.%06lds] [@%s:%d]", timebuf, tv.tv_usec, filename, line);
                                                       ^
    zlog/zlog.c:203:5: note: ‘snprintf’ output 17 or more bytes (assuming 144) into a destination of size 128
         snprintf(buffer, ZLOG_BUFFER_STR_MAX_LEN, "[%s.%06lds] [@%s:%d]", timebuf, tv.tv_usec, filename, line);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

Thanks for `zlog`! :)

**Comment by zma** [comment]
I pushed a quick fix. It is not perfect--the buffer for local time may be longer than the buffer.

But at least it avoids the warning messages.

```
$ gcc-8 -Wall example.c zlog.c -o example -lpthread
$ gcc-8 --version
gcc-8 (Ubuntu 8.3.0-6ubuntu1~18.04) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by pmembrey** [comment]
Confirmed that it avoids the warning for me too. Would be good to look at a more robust fix for a future version maybe but this is already an improvement :)

**Comment by pmembrey** [comment]
Did some quick tests - looks good. Thanks for taking care of this so quickly! :)

**Comment by zma** [comment]
Thanks for the confirmation.

So far, I would like to find some time to do some more revisions first to handle the cases when the `strftime()` returns 0 if the buffer is not large enough ( https://www.systutorials.com/docs/linux/man/3-strftime/ ) although it is rare. If `strftime()` fails, the library can fall back to the ! ZLOG_REAL_WORLD_TIME case.

**Comment by jwaggy** [comment]
Could you use ctime_r() for the datetime formatting which is guaranteed to be 26 bytes or less?

**Comment by zma** [comment]
@jwaggy ctime_r() sounds a better solution. Would you like to send some pull request?

**Comment by pmembrey** [comment]
This was fixed in master as of 44c5d8ac161b67a8f370ce9532cb36af866f78ee but current master fails to compile with the same error. Looks like a regression....

**Comment by pmembrey** [comment]
Looks like it was introduced in this commit: 93e66a824737fadf0245b8970b366e892bfd4b15

**Comment by zma** [comment]
I may take a little time and implement @jwaggy’s suggestion to fix this problem.

**Comment by zma** [comment]
The warnings should now be taken care of.
